# Generated by Django 4.1.3 on 2022-12-04 02:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ico.core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HandleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_start', models.IntegerField()),
                ('rank_end', models.IntegerField()),
                ('handled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ip_address', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('is_alive', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workers', models.ManyToManyField(blank=True, related_name='workers', to='core.worker')),
            ],
        ),
        migrations.CreateModel(
            name='QueryFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_file', models.FileField(upload_to=ico.core.models.QueryFile.upload_to)),
                ('handle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handle_version_id', to='core.handleversion')),
                ('version_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_version_id', to='core.version')),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=500)),
                ('query_type', models.CharField(max_length=255)),
                ('query_name', models.CharField(max_length=500, null=True)),
                ('ipv4_address', models.CharField(max_length=500, null=True)),
                ('ipv6_address', models.CharField(max_length=500, null=True)),
                ('as_number', models.CharField(max_length=500, null=True)),
                ('as_name', models.CharField(max_length=500, null=True)),
                ('bgp_prefix', models.CharField(max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='version_id', to='core.version')),
            ],
        ),
        migrations.AddField(
            model_name='handleversion',
            name='version_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handle_version_id', to='core.version'),
        ),
        migrations.AddField(
            model_name='handleversion',
            name='worker_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handle_worker_id', to='core.worker'),
        ),
    ]
