# Generated by Django 4.2 on 2023-04-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='provider',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
