# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build Docker image
    runs-on: self-hosted
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          load: true
          tags: ${{ secrets.DOCKER_USERNAME }}/ico-backend:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  deploy:
    name: Deploy Docker image
    needs: [build]
    runs-on: self-hosted
    steps:
      - name: Remove docker
        run: |
          if docker ps -a --format '{{.Names}}' | grep -q '${{ secrets.DOCKER_USERNAME }}-ico-backend'; then
            docker stop ${{ secrets.DOCKER_USERNAME }}-ico-backend
            docker rm -fv ${{ secrets.DOCKER_USERNAME }}-ico-backend
          fi
      - name: Run deploy
        run: docker run --name ${{ secrets.DOCKER_USERNAME }}-ico-backend -d -p 6070:80 -v /etc/ico:/etc/ico --restart unless-stopped --network="ico-network" "${{ secrets.DOCKER_USERNAME }}/ico-backend:latest"
